from tkinter import *
import tkinter as tk
from tkinter import ttk

root = tk.Tk()
root.geometry("250x350")
root.configure(background='Green')
root.title('USER DATA')

lbl = ttk.Label(root, text="Welcome to User Form", font=("Arial Bold", 15))
lbl.grid(column=0, row=0, columnspan=2, padx=18, pady=5)

id_lbl = ttk.Label(root, text="ID: ")
id_lbl.grid(column=0, row=1, padx=5, pady=5, sticky=W)
id_entry = ttk.Entry(root)
id_entry.grid(column=1, row=1, padx=5, pady=5)
user_lbl = ttk.Label(root, text="Username: ")
user_lbl.grid(column=0, row=2, padx=5, pady=5, sticky=W)
user_entry = ttk.Entry(root)
user_entry.grid(column=1, row=2)
pass_lbl = ttk.Label(root, text="Password: ")
pass_lbl.grid(column=0, row=3, padx=5, pady=5, sticky=W)
pass_entry = ttk.Entry(root)
pass_entry.grid(column=1, row=3)
email_lbl = ttk.Label(root, text="Email Id: ")
email_lbl.grid(column=0, row=4, padx=5, pady=5, sticky=W)
email_entry = ttk.Entry(root)
email_entry.grid(column=1, row=4)
phone_lbl = ttk.Label(root, text="Phone: ")
phone_lbl.grid(column=0, row=5, padx=5, pady=5, sticky=W)
phone_entry = ttk.Entry(root)
phone_entry.grid(column=1, row=5)
userT_lbl = ttk.Label(root, text="UserType: ")
userT_lbl.grid(column=0, row=6, padx=5, pady=5, sticky=W)
userT_entry = ttk.Entry(root)
userT_entry.grid(column=1, row=6)
status_lbl = ttk.Label(root, text="Status: ")
status_lbl.grid(column=0, row=7, padx=5, pady=5, sticky=W)
status_entry = ttk.Entry(root)
status_entry.grid(column=1, row=7)
submit_btn = ttk.Button(root, text="SUBMIT")
submit_btn.grid(column=1, row=8, padx=20, pady=5, sticky=E)

root.mainloop()
